## 4.5 读取和存储

然而在实际中，我们有时需要把训练好的模型部署到很多不同的设备。在这种情况下，我们可以把内存中训练好的模型参数存储在硬盘上供后续读取使用。

### 4.5.1 读写NDArray

我们可以直接使用save函数和load函数分别存储和读取NDArray。

In [4]:
from mxnet import nd
from mxnet.gluon import nn

x = nd.ones(3)
nd.save('x', x)

将数据从存储的文件读回内存

In [5]:
x2 = nd.load('x')
x2

[
 [1. 1. 1.]
 <NDArray 3 @cpu(0)>]

存储一列NDArray并读回内存

In [6]:
y = nd.zeros(4)
nd.save('xy', [x, y])
x2, y2 = nd.load('xy')
(x2, y2)

(
 [1. 1. 1.]
 <NDArray 3 @cpu(0)>,
 
 [0. 0. 0. 0.]
 <NDArray 4 @cpu(0)>)

存储并读取一个从字符串映射到NDArray的字典

In [7]:
mydict = {'x': x, 'y': y}
nd.save('mydict', mydict)
mydict2 = nd.load('mydict')
mydict2

{'x': 
 [1. 1. 1.]
 <NDArray 3 @cpu(0)>,
 'y': 
 [0. 0. 0. 0.]
 <NDArray 4 @cpu(0)>}

### 4.5.2 读写Gluon模型的参数

Gluon的Block类提供了save_parameters函数和load_parameters函数来读写模型参数。

In [8]:
class MLP(nn.Block):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.hidden = nn.Dense(256, activation='relu')
        self.output = nn.Dense(10)
        
    def forward(self, x):
        return self.output(self.hidden(x))
    
net = MLP()
net.initialize()
X = nd.random_uniform(shape=(2, 20))
Y = net(X)

下面把该模型的参数保存成文件，文件名为mlp.params

In [9]:
filename = 'mlp.params'
net.save_parameters(filename)

In [10]:
net2 = MLP()
net2.load_parameters(filename)

In [11]:
Y2 = net2(X)
Y2 == Y


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
<NDArray 2x10 @cpu(0)>

### 小结

- 通过save函数和load函数可以很方便地读写NDArray。
- 通过load_parameters函数和save_parameters函数可以很方便地读写Gluon模型的参数。

### 练习

- 即使⽆须把训练好的模型部署到不同的设备，存储模型参数在实际中还有哪些好处？

存储模型表现最佳时的参数，可以方便以后使用。